{% set name = "gocommands" %}
{% set version = "0.7.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: 'https://github.com/cyverse/gocommands'

build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:

about:
  home: 'https://github.com/cyverse/gocommands'
  summary: 'A protable command-line toolkit for iRODS'
  description: |
    gocommands is a portable command-line toolkit for iRODS data management service. 
    It can run on any systems, including linux, osx, and windows. As it is written in 
    pure Go language, it has no dependencies.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - iychoi
