{% set name = "gocommands" %}
{% set version = "0.7.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cyverse/gocommands/archive/v{{ version }}.tar.gz
  sha256: 777d412407099e1827466a38db759a5dd4106cd175a4457e448f11fe53342f96

build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:

about:
  home: https://github.com/cyverse/gocommands
  summary: 'A protable command-line toolkit for iRODS'
  description: |
    gocommands is a portable command-line toolkit for iRODS data management service. 
    It can run on any systems, including linux, osx, and windows. As it is written in 
    pure Go language, it has no dependencies.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/cyverse/gocommands

extra:
  recipe-maintainers:
    - iychoi
